// =============================================================================
// NR1 Pro - Tipos do Supabase (Database Types)
// Gerado automaticamente a partir do schema
// =============================================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      perfis: {
        Row: {
          id: string;
          email: string;
          nome: string;
          sobrenome: string | null;
          avatar_url: string | null;
          telefone: string | null;
          cargo: string | null;
          perfil: 'admin' | 'gestor' | 'usuario' | 'auditor';
          status: 'ativo' | 'inativo' | 'bloqueado' | 'pendente';
          mfa_enabled: boolean;
          mfa_secret: string | null;
          ultimo_acesso: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          nome: string;
          sobrenome?: string | null;
          avatar_url?: string | null;
          telefone?: string | null;
          cargo?: string | null;
          perfil?: 'admin' | 'gestor' | 'usuario' | 'auditor';
          status?: 'ativo' | 'inativo' | 'bloqueado' | 'pendente';
          mfa_enabled?: boolean;
          mfa_secret?: string | null;
          ultimo_acesso?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          nome?: string;
          sobrenome?: string | null;
          avatar_url?: string | null;
          telefone?: string | null;
          cargo?: string | null;
          perfil?: 'admin' | 'gestor' | 'usuario' | 'auditor';
          status?: 'ativo' | 'inativo' | 'bloqueado' | 'pendente';
          mfa_enabled?: boolean;
          mfa_secret?: string | null;
          ultimo_acesso?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      empresas: {
        Row: {
          id: string;
          nome_fantasia: string;
          razao_social: string | null;
          cnpj: string | null;
          inscricao_estadual: string | null;
          inscricao_municipal: string | null;
          cep: string | null;
          logradouro: string | null;
          numero: string | null;
          complemento: string | null;
          bairro: string | null;
          cidade: string | null;
          estado: string | null;
          telefone: string | null;
          email: string | null;
          site: string | null;
          logo_url: string | null;
          cor_primaria: string;
          cor_secundaria: string;
          plano: 'trial' | 'starter' | 'business' | 'enterprise';
          trial_ate: string | null;
          status: 'ativa' | 'inativa' | 'suspensa' | 'cancelada';
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          nome_fantasia: string;
          razao_social?: string | null;
          cnpj?: string | null;
          inscricao_estadual?: string | null;
          inscricao_municipal?: string | null;
          cep?: string | null;
          logradouro?: string | null;
          numero?: string | null;
          complemento?: string | null;
          bairro?: string | null;
          cidade?: string | null;
          estado?: string | null;
          telefone?: string | null;
          email?: string | null;
          site?: string | null;
          logo_url?: string | null;
          cor_primaria?: string;
          cor_secundaria?: string;
          plano?: 'trial' | 'starter' | 'business' | 'enterprise';
          trial_ate?: string | null;
          status?: 'ativa' | 'inativa' | 'suspensa' | 'cancelada';
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          nome_fantasia?: string;
          razao_social?: string | null;
          cnpj?: string | null;
          inscricao_estadual?: string | null;
          inscricao_municipal?: string | null;
          cep?: string | null;
          logradouro?: string | null;
          numero?: string | null;
          complemento?: string | null;
          bairro?: string | null;
          cidade?: string | null;
          estado?: string | null;
          telefone?: string | null;
          email?: string | null;
          site?: string | null;
          logo_url?: string | null;
          cor_primaria?: string;
          cor_secundaria?: string;
          plano?: 'trial' | 'starter' | 'business' | 'enterprise';
          trial_ate?: string | null;
          status?: 'ativa' | 'inativa' | 'suspensa' | 'cancelada';
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      usuarios_empresas: {
        Row: {
          id: string;
          usuario_id: string;
          empresa_id: string;
          perfil: 'admin' | 'gestor' | 'usuario' | 'auditor';
          departamento: string | null;
          matricula: string | null;
          data_admissao: string | null;
          is_principal: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          usuario_id: string;
          empresa_id: string;
          perfil?: 'admin' | 'gestor' | 'usuario' | 'auditor';
          departamento?: string | null;
          matricula?: string | null;
          data_admissao?: string | null;
          is_principal?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          usuario_id?: string;
          empresa_id?: string;
          perfil?: 'admin' | 'gestor' | 'usuario' | 'auditor';
          departamento?: string | null;
          matricula?: string | null;
          data_admissao?: string | null;
          is_principal?: boolean;
          created_at?: string;
        };
      };
      funcionarios: {
        Row: {
          id: string;
          empresa_id: string;
          nome_completo: string;
          cpf: string | null;
          rg: string | null;
          data_nascimento: string | null;
          sexo: 'M' | 'F' | 'O' | null;
          estado_civil: string | null;
          cep: string | null;
          logradouro: string | null;
          numero: string | null;
          complemento: string | null;
          bairro: string | null;
          cidade: string | null;
          estado: string | null;
          telefone: string | null;
          celular: string | null;
          email: string | null;
          matricula: string | null;
          cargo: string | null;
          departamento: string | null;
          data_admissao: string | null;
          data_demissao: string | null;
          tipo_contrato: 'clt' | 'pj' | 'estagio' | 'temporario';
          pis_pasep: string | null;
          ctps_numero: string | null;
          ctps_serie: string | null;
          ctps_uf: string | null;
          status: 'ativo' | 'afastado' | 'ferias' | 'demissional' | 'inativo';
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          nome_completo: string;
          cpf?: string | null;
          rg?: string | null;
          data_nascimento?: string | null;
          sexo?: 'M' | 'F' | 'O' | null;
          estado_civil?: string | null;
          cep?: string | null;
          logradouro?: string | null;
          numero?: string | null;
          complemento?: string | null;
          bairro?: string | null;
          cidade?: string | null;
          estado?: string | null;
          telefone?: string | null;
          celular?: string | null;
          email?: string | null;
          matricula?: string | null;
          cargo?: string | null;
          departamento?: string | null;
          data_admissao?: string | null;
          data_demissao?: string | null;
          tipo_contrato?: 'clt' | 'pj' | 'estagio' | 'temporario';
          pis_pasep?: string | null;
          ctps_numero?: string | null;
          ctps_serie?: string | null;
          ctps_uf?: string | null;
          status?: 'ativo' | 'afastado' | 'ferias' | 'demissional' | 'inativo';
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          nome_completo?: string;
          cpf?: string | null;
          rg?: string | null;
          data_nascimento?: string | null;
          sexo?: 'M' | 'F' | 'O' | null;
          estado_civil?: string | null;
          cep?: string | null;
          logradouro?: string | null;
          numero?: string | null;
          complemento?: string | null;
          bairro?: string | null;
          cidade?: string | null;
          estado?: string | null;
          telefone?: string | null;
          celular?: string | null;
          email?: string | null;
          matricula?: string | null;
          cargo?: string | null;
          departamento?: string | null;
          data_admissao?: string | null;
          data_demissao?: string | null;
          tipo_contrato?: 'clt' | 'pj' | 'estagio' | 'temporario';
          pis_pasep?: string | null;
          ctps_numero?: string | null;
          ctps_serie?: string | null;
          ctps_uf?: string | null;
          status?: 'ativo' | 'afastado' | 'ferias' | 'demissional' | 'inativo';
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      asos: {
        Row: {
          id: string;
          empresa_id: string;
          funcionario_id: string;
          tipo_aso: 'admissional' | 'demissional' | 'periodico' | 'retorno' | 'mudanca_funcao' | 'risco_especial';
          data_exame: string;
          data_validade: string | null;
          apto: boolean | null;
          restricoes: string | null;
          observacoes: string | null;
          medico_nome: string | null;
          medico_crm: string | null;
          medico_uf: string | null;
          arquivo_url: string | null;
          status: 'pendente' | 'aprovado' | 'reprovado' | 'vencido';
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          funcionario_id: string;
          tipo_aso: 'admissional' | 'demissional' | 'periodico' | 'retorno' | 'mudanca_funcao' | 'risco_especial';
          data_exame: string;
          data_validade?: string | null;
          apto?: boolean | null;
          restricoes?: string | null;
          observacoes?: string | null;
          medico_nome?: string | null;
          medico_crm?: string | null;
          medico_uf?: string | null;
          arquivo_url?: string | null;
          status?: 'pendente' | 'aprovado' | 'reprovado' | 'vencido';
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          funcionario_id?: string;
          tipo_aso?: 'admissional' | 'demissional' | 'periodico' | 'retorno' | 'mudanca_funcao' | 'risco_especial';
          data_exame?: string;
          data_validade?: string | null;
          apto?: boolean | null;
          restricoes?: string | null;
          observacoes?: string | null;
          medico_nome?: string | null;
          medico_crm?: string | null;
          medico_uf?: string | null;
          arquivo_url?: string | null;
          status?: 'pendente' | 'aprovado' | 'reprovado' | 'vencido';
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      exames: {
        Row: {
          id: string;
          empresa_id: string;
          funcionario_id: string;
          tipo_exame: string;
          data_solicitacao: string | null;
          data_realizacao: string | null;
          data_resultado: string | null;
          resultado: string | null;
          observacoes: string | null;
          arquivo_url: string | null;
          status: 'solicitado' | 'agendado' | 'realizado' | 'resultado_disponivel' | 'cancelado';
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          funcionario_id: string;
          tipo_exame: string;
          data_solicitacao?: string | null;
          data_realizacao?: string | null;
          data_resultado?: string | null;
          resultado?: string | null;
          observacoes?: string | null;
          arquivo_url?: string | null;
          status?: 'solicitado' | 'agendado' | 'realizado' | 'resultado_disponivel' | 'cancelado';
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          funcionario_id?: string;
          tipo_exame?: string;
          data_solicitacao?: string | null;
          data_realizacao?: string | null;
          data_resultado?: string | null;
          resultado?: string | null;
          observacoes?: string | null;
          arquivo_url?: string | null;
          status?: 'solicitado' | 'agendado' | 'realizado' | 'resultado_disponivel' | 'cancelado';
          created_at?: string;
          created_by?: string | null;
        };
      };
      acidentes: {
        Row: {
          id: string;
          empresa_id: string;
          funcionario_id: string;
          data_acidente: string;
          hora_acidente: string | null;
          local_acidente: string | null;
          descricao: string;
          tipo_acidente: 'tipico' | 'trajeto' | 'doenca_profissional' | 'doenca_trabalho' | null;
          natureza_lesao: string | null;
          parte_corpo: string | null;
          cat_emitida: boolean;
          cat_numero: string | null;
          cat_data_emissao: string | null;
          afastamento_dias: number | null;
          afastamento_inicio: string | null;
          afastamento_fim: string | null;
          causas: string | null;
          medidas_adotadas: string | null;
          testemunhas: string | null;
          status: 'registrado' | 'investigacao' | 'concluido' | 'arquivado';
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          funcionario_id: string;
          data_acidente: string;
          hora_acidente?: string | null;
          local_acidente?: string | null;
          descricao: string;
          tipo_acidente?: 'tipico' | 'trajeto' | 'doenca_profissional' | 'doenca_trabalho' | null;
          natureza_lesao?: string | null;
          parte_corpo?: string | null;
          cat_emitida?: boolean;
          cat_numero?: string | null;
          cat_data_emissao?: string | null;
          afastamento_dias?: number | null;
          afastamento_inicio?: string | null;
          afastamento_fim?: string | null;
          causas?: string | null;
          medidas_adotadas?: string | null;
          testemunhas?: string | null;
          status?: 'registrado' | 'investigacao' | 'concluido' | 'arquivado';
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          funcionario_id?: string;
          data_acidente?: string;
          hora_acidente?: string | null;
          local_acidente?: string | null;
          descricao?: string;
          tipo_acidente?: 'tipico' | 'trajeto' | 'doenca_profissional' | 'doenca_trabalho' | null;
          natureza_lesao?: string | null;
          parte_corpo?: string | null;
          cat_emitida?: boolean;
          cat_numero?: string | null;
          cat_data_emissao?: string | null;
          afastamento_dias?: number | null;
          afastamento_inicio?: string | null;
          afastamento_fim?: string | null;
          causas?: string | null;
          medidas_adotadas?: string | null;
          testemunhas?: string | null;
          status?: 'registrado' | 'investigacao' | 'concluido' | 'arquivado';
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      notificacoes: {
        Row: {
          id: string;
          usuario_id: string;
          titulo: string;
          mensagem: string;
          tipo: 'info' | 'success' | 'warning' | 'error';
          link: string | null;
          link_text: string | null;
          lida: boolean;
          lida_em: string | null;
          agendada_para: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          usuario_id: string;
          titulo: string;
          mensagem: string;
          tipo?: 'info' | 'success' | 'warning' | 'error';
          link?: string | null;
          link_text?: string | null;
          lida?: boolean;
          lida_em?: string | null;
          agendada_para?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          usuario_id?: string;
          titulo?: string;
          mensagem?: string;
          tipo?: 'info' | 'success' | 'warning' | 'error';
          link?: string | null;
          link_text?: string | null;
          lida?: boolean;
          lida_em?: string | null;
          agendada_para?: string | null;
          created_at?: string;
        };
      };
      sessoes: {
        Row: {
          id: string;
          usuario_id: string;
          device_id: string;
          device_name: string | null;
          device_type: string | null;
          ip_address: unknown | null;
          user_agent: string | null;
          location: string | null;
          refresh_token_hash: string | null;
          ultima_atividade: string;
          expira_em: string;
          revoked_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          usuario_id: string;
          device_id: string;
          device_name?: string | null;
          device_type?: string | null;
          ip_address?: unknown | null;
          user_agent?: string | null;
          location?: string | null;
          refresh_token_hash?: string | null;
          ultima_atividade?: string;
          expira_em: string;
          revoked_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          usuario_id?: string;
          device_id?: string;
          device_name?: string | null;
          device_type?: string | null;
          ip_address?: unknown | null;
          user_agent?: string | null;
          location?: string | null;
          refresh_token_hash?: string | null;
          ultima_atividade?: string;
          expira_em?: string;
          revoked_at?: string | null;
          created_at?: string;
        };
      };
      auditoria_logs: {
        Row: {
          id: string;
          usuario_id: string | null;
          empresa_id: string | null;
          acao: string;
          entidade: string;
          entidade_id: string | null;
          dados_anteriores: Json | null;
          dados_novos: Json | null;
          ip_address: unknown | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          usuario_id?: string | null;
          empresa_id?: string | null;
          acao: string;
          entidade: string;
          entidade_id?: string | null;
          dados_anteriores?: Json | null;
          dados_novos?: Json | null;
          ip_address?: unknown | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          usuario_id?: string | null;
          empresa_id?: string | null;
          acao?: string;
          entidade?: string;
          entidade_id?: string | null;
          dados_anteriores?: Json | null;
          dados_novos?: Json | null;
          ip_address?: unknown | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
